// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmIXAnpuyHDRuzkaUB_x4oCFPGn4H3s2o',
    appId: '1:512006922418:web:6cadbbc1d107a3d0af69ab',
    messagingSenderId: '512006922418',
    projectId: 'app1-e94bd',
    authDomain: 'app1-e94bd.firebaseapp.com',
    storageBucket: 'app1-e94bd.firebasestorage.app',
    measurementId: 'G-BNPVVXV40N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyAUqw84Gi4PkfWETKsPE1ZyNcwREVQmU',
    appId: '1:512006922418:android:35f3803de8f7608eaf69ab',
    messagingSenderId: '512006922418',
    projectId: 'app1-e94bd',
    storageBucket: 'app1-e94bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ1HFYc-DOPk8iLpf9n7GLT60CCur6cpM',
    appId: '1:512006922418:ios:202ca5f6d8849a2faf69ab',
    messagingSenderId: '512006922418',
    projectId: 'app1-e94bd',
    storageBucket: 'app1-e94bd.firebasestorage.app',
    iosBundleId: 'com.example.demoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ1HFYc-DOPk8iLpf9n7GLT60CCur6cpM',
    appId: '1:512006922418:ios:202ca5f6d8849a2faf69ab',
    messagingSenderId: '512006922418',
    projectId: 'app1-e94bd',
    storageBucket: 'app1-e94bd.firebasestorage.app',
    iosBundleId: 'com.example.demoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmIXAnpuyHDRuzkaUB_x4oCFPGn4H3s2o',
    appId: '1:512006922418:web:c25e5dba0ca567b9af69ab',
    messagingSenderId: '512006922418',
    projectId: 'app1-e94bd',
    authDomain: 'app1-e94bd.firebaseapp.com',
    storageBucket: 'app1-e94bd.firebasestorage.app',
    measurementId: 'G-YZ8PVJEHW7',
  );
}
